force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This record type will be used to create customer records by the NDIA users</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/NDIA_Primary_Owner__c.field-meta.xml
<CustomField>
    <fullName>NDIA_Primary_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NDIA Primary Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/NDIAAccount__c.field-meta.xml
<CustomField>
    <fullName>NDIAAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

NDAUAT/force-app/main/default/objects/Quotation__c/fields/NDIAApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>NDIAApprovalDate__c</fullName>
    <label>Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/NDIANDIS_Number__c.field-meta.xml
<CustomField>
    <fullName>NDIANDIS_Number__c</fullName>
    <formula>NDIAAccount__r.NDIANDISNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NDIS Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/NDIAQuoteStage__c.field-meta.xml
<CustomField>
    <fullName>NDIAQuoteStage__c</fullName>
    <label>Quote Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not yet commenced</fullName>
                <default>true</default>
                <label>Not yet commenced</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approval In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/NDIAQuoteType__c.field-meta.xml
<CustomField>
    <fullName>NDIAQuoteType__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIL</fullName>
            </value>
            <value>
                <fullName>Assistive Technology</fullName>
            </value>
            <value>
                <fullName>Home Modifications</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/NDIAWeeklyApprovedAmount__c.field-meta.xml
<CustomField>
    <fullName>NDIAWeeklyApprovedAmount__c</fullName>
    <label>Weekly Approved Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UATPACKAGE/force-app/main/default/objects/Quotation__c/fields/NDIAWeeklyOfferedAmount__c.field-meta.xml
<CustomField>
    <fullName>NDIAWeeklyOfferedAmount__c</fullName>
    <label>Weekly Offered Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/NDIAWeeklyQuotedAmount__c.field-meta.xml
<CustomField>
    <fullName>NDIAWeeklyQuotedAmount__c</fullName>
    <label>Weekly Quoted Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UATPACKAGE/force-app/main/default/objects/Quotation__c/fields/NDIAWeeklyServiceBookingValue__c.field-meta.xml
<CustomField>
    <fullName>NDIAWeeklyServiceBookingValue__c</fullName>
    <label>Weekly Service Booking Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/NDIAAssignNdiaPrimaryOwnerCtrlTest.cls
/**
*
* @date: 20-11-2019
* @author: Amiya Das
* @description: test class for AssignNdiaPrimaryOwnerCtrl
* @param <Input parameter 1>
* @param <Input parameter 2>
*/
@isTest
public class NDIAAssignNdiaPrimaryOwnerCtrlTest {
    
    public static testmethod void fetchUserToUpdateRecordTest(){
        
        // invoking NDIATestDataFactory for inserting account
        /*   Account objAccount = NDIATestDataFactory.createCustomer();
insert objAccount;
system.assert(objAccount.Id != null);

// invoking NDIATestDataFactory for inserting User
User objUser = NDIATestDataFactory.createNDIAUser();
insert objUser;
system.assert(objUser.Id != null);

// invoking NDIATestDataFactory for inserting Quotation with Customer and NDIA Primary Owner
Quotation__c objQuotation = NDIATestDataFactory.createQuotationWithNDIAOwner(objAccount.Id, objUser.Id);
insert objQuotation;
system.assert(objQuotation.Id != null);   */
        
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        
        
        
        Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
        User portalAccountOwner1 = new User(
            UserRoleId = portalRole.Id,
            ProfileId = profile1.Id,
            Username = System.now().millisecond() + 'test2@test.com',
            Alias = 'batman',
            Email='bruce.wayne@wayneenterprises.com',
            EmailEncodingKey='UTF-8',
            Firstname='Bruce',
            Lastname='Wayne',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Chicago'
        );
        insert portalAccountOwner1;
        
        system.runAs(portalAccountOwner1){
            
            Account portalAccount1 = new Account();
            portalAccount1.Name = 'TestAccount';
            portalAccount1.OwnerId = portalAccountOwner1.Id;
            portalAccount1.BillingStreet = 'TestAccount';
            portalAccount1.BillingCity = 'testAccount';
            portalAccount1.BillingState = 'New South Wales';
            portalAccount1.BillingPostalCode = '2000';
            portalAccount1.BillingCountry = 'Australia';
            
            
            insert portalAccount1;
            
            Contact con1 = new Contact();
            con1.FirstName = 'Test';
            con1.Lastname = 'McTesty';
            con1.AccountId = portalAccount1.Id;
            con1.Email = System.now().millisecond() + 'test@test.com';
            insert con1;
            
            
            
            
            
            // create user
            Profile portalProfile = [SELECT Id FROM Profile where name = 'NDIAUser'];
            User user1 = new User(
                Username = System.now().millisecond() + 'test12345@test.com',
                ContactId = con1.Id,
                ProfileId = portalProfile.Id,
                Alias = 'test123',
                Email = 'test12345@test.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'McTesty',
                CommunityNickname = 'test12345',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US'
            );
            insert user1; 
            
            
            /*  Quotation__c objQuotation = NDIATestDataFactory.createQuotationWithNDIAOwner(portalAccount1.Id, user1.Id);
insert objQuotation;
system.assert(objQuotation.Id != null); */
            
            Quotation__c objQuotationWithNDIAOwner = new Quotation__c();
            objQuotationWithNDIAOwner.NDIAAccount__c = portalAccount1.Id;
            objQuotationWithNDIAOwner.NDIAApprovalDate__c = System.today();
            objQuotationWithNDIAOwner.NDIAQuoteType__c = 'SIL';
            objQuotationWithNDIAOwner.NDIAWeeklyApprovedAmount__c = 1.00;
            objQuotationWithNDIAOwner.NDIAWeeklyOfferedAmount__c = 1.00;
            objQuotationWithNDIAOwner.NDIAWeeklyQuotedAmount__c = 2.00; 
            objQuotationWithNDIAOwner.NDIAWeeklyServiceBookingValue__c = 3.00;
            objQuotationWithNDIAOwner.NDIA_Primary_Owner__c = user1.Id;
            insert objQuotationWithNDIAOwner;
            
            
            
            test.startTest();
            AssignNdiaPrimaryOwnerCtrl.fetchUserToUpdateRecord(objQuotationWithNDIAOwner.Id);
            test.stopTest();
            
            /*  if(objQuotationWithNDIAOwner.Id == null){
insert objQuotationWithNDIAOwner;

} */
        }
    }
    
    public static testmethod void primaryOwnerNotAssgnTest(){
        
        /*   Quotation__c objQuotationApproval1 = new Quotation__c();
//   objQuotationApproval.NDIAAccount__c = accountId;
objQuotationApproval1.NDIAApprovalDate__c = System.today();
objQuotationApproval1.NDIAQuoteType__c = 'SIL';
objQuotationApproval1.NDIAWeeklyApprovedAmount__c = 1.00;
objQuotationApproval1.NDIAWeeklyOfferedAmount__c = 1.00;
objQuotationApproval1.NDIAWeeklyQuotedAmount__c = 2.00; 
objQuotationApproval1.NDIAWeeklyServiceBookingValue__c = 3.00;
objQuotationApproval1.NDIAQuoteStage__c='Approval In Progress'; */
        //   objQuotationApproval1.NDIA_Primary_Owner__c = UserInfo.getUserId();
        //  objQuotationApproval.NDIANDIS_Number__c = ndisNum;
        //  insert objQuotationApproval1;
        //  system.assert(objQuotationApproval1.Id = null); 
        
        Quotation__C objQuoteWOPriOnwer = NDIATestDataFactory.CrQuoteWithoutPriOwner();
        insert objQuoteWOPriOnwer;
        system.assert(objQuoteWOPriOnwer.Id != null);
        
        test.startTest();
        AssignNdiaPrimaryOwnerCtrl.fetchUserToUpdateRecord(objQuoteWOPriOnwer.Id);
        test.stopTest(); 
        
    }
    
}