force-app/main/default/objects/Account/fields/NDIANDISParticipant__c.field-meta.xml
<CustomField>
    <fullName>NDIANDISParticipant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NDIS Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/NDIANDISParticipant__c.field-meta.xml
<CustomField>
    <fullName>NDIANDISParticipant__c</fullName>
    <formula>NDIAAccount__r.NDIANDISParticipant__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NDIS Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/NDIAQuoteStage__c.field-meta.xml
<CustomField>
    <fullName>NDIAQuoteStage__c</fullName>
    <label>Quote Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not yet commenced</fullName>
                <default>true</default>
                <label>Not yet commenced</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approval In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NDIAUserTriggerHandler.cls
public class NDIAUserTriggerHandler
{
    public  void addMembertoNDIAGroup(List<User> ndiaUser)
    {
        List<Id> userId = new List<Id>();
        for(User U : ndiaUser) {
            if(U.isActive) {
                userId.add(U.Id);
            }
        }
        
        updateGroupMemberList(userId);
        
    }
    @future
    
    private static void updateGroupMemberList(List<Id> userId)
        
    {
        string ndiaPublicGroupName=System.Label.NDIAPublicGroupName;
        string ndiaProfileName=System.Label.ndiaProfileName;
        if(Schema.SObjectType.Quotation__c.isCreateable() && Schema.SObjectType.Quotation__c.Fields.NDIAQuoteStage__c.isCreateable()
           &&Schema.SObjectType.Quotation__c.Fields.NDIANDISParticipant__c.isCreateable()&&
           Schema.SObjectType.Account.isAccessible()){
               User u = [ Select id,user.profile.name from User where Id = :userId[0]];
               system.debug('u'+STring.valueOf(user.profile.name)==ndiaProfileName);
               if(u.profile.name!=null && STring.valueOf(u.profile.name)==ndiaProfileName){
                   List<Group> ndiaGroup=[SELECT Id, DeveloperName, (SELECT Id, UserOrGroupId FROM GroupMembers)FROM Group where DeveloperName=:ndiaPublicGroupName WITH SECURITY_ENFORCED];
                   List<GroupMember> GMlist = new List<GroupMember>();

                   if(Schema.SObjectType.GroupMember.isCreateable())
                   {
                       if(Schema.SObjectType.GroupMember.Fields.GroupId.isCreateable() && Schema.SObjectType.GroupMember.Fields.UserOrGroupId.isCreateable())
                       {
                   GroupMember GM = new GroupMember();
                   GM.GroupId = ndiaGroup[0].Id;
                   GM.UserOrGroupId = u.Id;
                   GMList.add(GM); 
                   }  
                   }
                   if(!GMList.isEmpty()) {
                       System.debug('Group Member List is ' + GMList);
                       insert GMList;
                   }
}
               
               
           }
    }
}