force-app/main/default/objects/User/fields/NDIAFullAccessRequest__c.field-meta.xml
<CustomField>
    <fullName>NDIAFullAccessRequest__c</fullName>
    <label>Full Access Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/NDIARequestCheck__c.field-meta.xml
<CustomField>
    <fullName>NDIARequestCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NDIAFullAccessRequestContrTest.cls
/**
*
* @date: 30-11-2019
* @author: Amiya Das
* @description: test class for 'NDIAFullAccessRequestController'
* @param <Input parameter 1>
* @param <Input parameter 2>
*/
@isTest
public with sharing class NDIAFullAccessRequestContrTest {
    
    public static testmethod void testCreatePaidAcessRecord(){

       
       User u = [Select id, name, email, NDIAFullAccessRequest__c, NDIARequestCheck__c from User 
                  where id=: UserInfo.getUserId()];
       //system.runAs(u){
         u.NDIAFullAccessRequest__c = 'Requested';
         update u;
      //  } 

      test.startTest();
      NDIAFullAccessRequestController.createPaidAcessRecord();
      test.stopTest();
}
public static testmethod void testCreatePaidAcessRecord1(){

    User u = [Select id, name, email, NDIAFullAccessRequest__c, NDIARequestCheck__c from User 
                  where id=: UserInfo.getUserId()];
       //system.runAs(u){
         u.NDIAFullAccessRequest__c = 'Activated';
         update u;
      //  } 

      test.startTest();
      NDIAFullAccessRequestController.createPaidAcessRecord();
      test.stopTest();
}
}