NDAUAT/force-app/main/default/objects/NDIATriggerSwitch__c/NDIATriggerSwitch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Manage on and Off of  trigger</description>
    <label>NDIATriggerSwitch</label>
</CustomObject>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/NDIAQuoteStage__c.field-meta.xml
<CustomField>
    <fullName>NDIAQuoteStage__c</fullName>
    <label>Quote Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not yet commenced</fullName>
                <default>true</default>
                <label>Not yet commenced</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approval In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UATPACKAGE/force-app/main/default/objects/Quotation__c/fields/NDIAWeeklyServiceBookingValue__c.field-meta.xml
<CustomField>
    <fullName>NDIAWeeklyServiceBookingValue__c</fullName>
    <label>Weekly Service Booking Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

NDIATESTCLASSES/force-app/main/default/classes/NDIAQuoteTriggerTest.cls
/*This trigger is written to cover quotation trigger
----------------------------------Mukul Mishra--------------------------
----------------------------------04/11/2019----------------------------
------------------------------User story -0006 ------------------------- */
@isTest
public class NDIAQuoteTriggerTest {
    @isTest
    public static void checkSharing()
    {
        NDIATriggerSwitch__c objTriggerSwitch=NDIATestDataFactory.createTriggerSwitch();
        Account objCustomer= NDIATestDataFactory.createCustomer();
        insert objCustomer;
        Quotation__c objQuotation=NDIATestDataFactory.createQuotation(objCustomer.Id);
        insert objQuotation;
        system.debug('objQuotation'+objQuotation);
        
        
        test.startTest();
        list<ContentDocument> lstContentDoc= NDIATestDataFactory.createContentDocument();
        List<ContentDocumentLink> lstContentDocLink= NDIATestDataFactory.insertContentDocumentLink();
        for(ContentDocumentLink objContentDocumentLink: lstContentDocLink )
        {
            objContentDocumentLink.LinkedEntityId=objQuotation.id;
            objContentDocumentLink.ContentDocumentId=lstContentDoc[0].Id;
        }
        insert lstContentDocLink;
        objQuotation.NDIAWeeklyServiceBookingValue__c=3.10;
        objQuotation.NDIAQuoteStage__c='Final';
        update objQuotation;
        objQuotation.NDIAQuoteStage__c='Submitted';
        
        update objQuotation;
        test.stopTest();
        
    }
    
}